package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminPlanMaster generated by hbm2java
 */
@Entity
@Table(name="admin_plan_master"
    ,catalog="onlinejobportal"
)
public class AdminPlanMaster  implements java.io.Serializable {


     private Integer planId;
     private String planType;
     private String durationMode;
     private String duration;
     private String rent;
     private String specification;

    public AdminPlanMaster() {
    }

    public AdminPlanMaster(String planType, String durationMode, String duration, String rent, String specification) {
       this.planType = planType;
       this.durationMode = durationMode;
       this.duration = duration;
       this.rent = rent;
       this.specification = specification;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="planId", unique=true, nullable=false)
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    
    @Column(name="plan_type", nullable=false, length=20)
    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }

    
    @Column(name="duration_mode", nullable=false, length=6)
    public String getDurationMode() {
        return this.durationMode;
    }
    
    public void setDurationMode(String durationMode) {
        this.durationMode = durationMode;
    }

    
    @Column(name="duration", nullable=false, length=4)
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }

    
    @Column(name="rent", nullable=false, length=8)
    public String getRent() {
        return this.rent;
    }
    
    public void setRent(String rent) {
        this.rent = rent;
    }

    
    @Column(name="specification", nullable=false, length=70)
    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }




}


