package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminArticles generated by hbm2java
 */
@Entity
@Table(name="admin_articles"
    ,catalog="onlinejobportal"
)
public class AdminArticles  implements java.io.Serializable {


     private Integer articalId;
     private String articalName;
     private Date postedOn;
     private String articalDesc;

    public AdminArticles() {
    }

    public AdminArticles(String articalName, Date postedOn, String articalDesc) {
       this.articalName = articalName;
       this.postedOn = postedOn;
       this.articalDesc = articalDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="artical_id", unique=true, nullable=false)
    public Integer getArticalId() {
        return this.articalId;
    }
    
    public void setArticalId(Integer articalId) {
        this.articalId = articalId;
    }

    
    @Column(name="artical_name", nullable=false, length=200)
    public String getArticalName() {
        return this.articalName;
    }
    
    public void setArticalName(String articalName) {
        this.articalName = articalName;
    }

    
    @Column(name="posted_on", nullable=false, length=45)
    public Date getPostedOn() {
        return this.postedOn;
    }
    
    public void setPostedOn(Date postedOn) {
        this.postedOn = postedOn;
    }

    
    @Column(name="articalDesc", nullable=false, length=200)
    public String getArticalDesc() {
        return this.articalDesc;
    }
    
    public void setArticalDesc(String articalDesc) {
        this.articalDesc = articalDesc;
    }




}


