package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmindUseridandpassword generated by hbm2java
 */
@Entity
@Table(name="admind_useridandpassword"
    ,catalog="onlinejobportal"
)
public class AdmindUseridandpassword  implements java.io.Serializable {


     private String username;
     private String password;
     private Set<AuthTable3> authTable3s = new HashSet<AuthTable3>(0);

    public AdmindUseridandpassword() {
    }

	
    public AdmindUseridandpassword(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public AdmindUseridandpassword(String username, String password, Set<AuthTable3> authTable3s) {
       this.username = username;
       this.password = password;
       this.authTable3s = authTable3s;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admindUseridandpassword")
    public Set<AuthTable3> getAuthTable3s() {
        return this.authTable3s;
    }
    
    public void setAuthTable3s(Set<AuthTable3> authTable3s) {
        this.authTable3s = authTable3s;
    }




}


