package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthTable2 generated by hbm2java
 */
@Entity
@Table(name="auth_table2"
    ,catalog="onlinejobportal"
)
public class AuthTable2  implements java.io.Serializable {


     private Integer authId;
     private EmployeeUsernameAndPassword employeeUsernameAndPassword;
     private String status;

    public AuthTable2() {
    }

    public AuthTable2(EmployeeUsernameAndPassword employeeUsernameAndPassword, String status) {
       this.employeeUsernameAndPassword = employeeUsernameAndPassword;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="auth_id", unique=true, nullable=false)
    public Integer getAuthId() {
        return this.authId;
    }
    
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public EmployeeUsernameAndPassword getEmployeeUsernameAndPassword() {
        return this.employeeUsernameAndPassword;
    }
    
    public void setEmployeeUsernameAndPassword(EmployeeUsernameAndPassword employeeUsernameAndPassword) {
        this.employeeUsernameAndPassword = employeeUsernameAndPassword;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


