package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthTable3 generated by hbm2java
 */
@Entity
@Table(name="auth_table3"
    ,catalog="onlinejobportal"
)
public class AuthTable3  implements java.io.Serializable {


     private Integer authId;
     private AdmindUseridandpassword admindUseridandpassword;
     private String status;

    public AuthTable3() {
    }

    public AuthTable3(AdmindUseridandpassword admindUseridandpassword, String status) {
       this.admindUseridandpassword = admindUseridandpassword;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="auth_id", unique=true, nullable=false)
    public Integer getAuthId() {
        return this.authId;
    }
    
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public AdmindUseridandpassword getAdmindUseridandpassword() {
        return this.admindUseridandpassword;
    }
    
    public void setAdmindUseridandpassword(AdmindUseridandpassword admindUseridandpassword) {
        this.admindUseridandpassword = admindUseridandpassword;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


