package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ComposeMessage generated by hbm2java
 */
@Entity
@Table(name="compose_message"
    ,catalog="onlinejobportal"
)
public class ComposeMessage  implements java.io.Serializable {


     private int loginid;
     private Login login;
     private Date date;
     private String sendTo;
     private String message;
     private String type;
     private String username;

    public ComposeMessage() {
    }

    public ComposeMessage(Login login, Date date, String sendTo, String message, String type, String username) {
       this.login = login;
       this.date = date;
       this.sendTo = sendTo;
       this.message = message;
       this.type = type;
       this.username = username;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="login"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="loginid", unique=true, nullable=false)
    public int getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(int loginid) {
        this.loginid = loginid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="send_to", nullable=false, length=45)
    public String getSendTo() {
        return this.sendTo;
    }
    
    public void setSendTo(String sendTo) {
        this.sendTo = sendTo;
    }

    
    @Column(name="message", nullable=false, length=45)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


