package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Consultancy generated by hbm2java
 */
@Entity
@Table(name="consultancy"
    ,catalog="onlinejobportal"
)
public class Consultancy  implements java.io.Serializable {


     private String consultantEmailid;
     private String password;

    public Consultancy() {
    }

    public Consultancy(String consultantEmailid, String password) {
       this.consultantEmailid = consultantEmailid;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="consultant_emailid", unique=true, nullable=false, length=20)
    public String getConsultantEmailid() {
        return this.consultantEmailid;
    }
    
    public void setConsultantEmailid(String consultantEmailid) {
        this.consultantEmailid = consultantEmailid;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


