package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeContact generated by hbm2java
 */
@Entity
@Table(name="employee_contact"
    ,catalog="onlinejobportal"
)
public class EmployeeContact  implements java.io.Serializable {


     private String username;
     private String empName;
     private String empDesg;
     private int empNumber;
     private String empCmpName;
     private String empCompAddress;
     private String empCompState;
     private String empCompCity;
     private String empCompanyProfile;
     private String empCompWebsite;

    public EmployeeContact() {
    }

    public EmployeeContact(String username, String empName, String empDesg, int empNumber, String empCmpName, String empCompAddress, String empCompState, String empCompCity, String empCompanyProfile, String empCompWebsite) {
       this.username = username;
       this.empName = empName;
       this.empDesg = empDesg;
       this.empNumber = empNumber;
       this.empCmpName = empCmpName;
       this.empCompAddress = empCompAddress;
       this.empCompState = empCompState;
       this.empCompCity = empCompCity;
       this.empCompanyProfile = empCompanyProfile;
       this.empCompWebsite = empCompWebsite;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="emp_name", nullable=false, length=45)
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    
    @Column(name="emp_desg", nullable=false, length=45)
    public String getEmpDesg() {
        return this.empDesg;
    }
    
    public void setEmpDesg(String empDesg) {
        this.empDesg = empDesg;
    }

    
    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    
    @Column(name="emp_cmpName", nullable=false, length=45)
    public String getEmpCmpName() {
        return this.empCmpName;
    }
    
    public void setEmpCmpName(String empCmpName) {
        this.empCmpName = empCmpName;
    }

    
    @Column(name="emp_compAddress", nullable=false, length=45)
    public String getEmpCompAddress() {
        return this.empCompAddress;
    }
    
    public void setEmpCompAddress(String empCompAddress) {
        this.empCompAddress = empCompAddress;
    }

    
    @Column(name="emp_compState", nullable=false, length=45)
    public String getEmpCompState() {
        return this.empCompState;
    }
    
    public void setEmpCompState(String empCompState) {
        this.empCompState = empCompState;
    }

    
    @Column(name="emp_compCity", nullable=false, length=45)
    public String getEmpCompCity() {
        return this.empCompCity;
    }
    
    public void setEmpCompCity(String empCompCity) {
        this.empCompCity = empCompCity;
    }

    
    @Column(name="emp_companyProfile", nullable=false, length=45)
    public String getEmpCompanyProfile() {
        return this.empCompanyProfile;
    }
    
    public void setEmpCompanyProfile(String empCompanyProfile) {
        this.empCompanyProfile = empCompanyProfile;
    }

    
    @Column(name="emp_comp_website", nullable=false, length=45)
    public String getEmpCompWebsite() {
        return this.empCompWebsite;
    }
    
    public void setEmpCompWebsite(String empCompWebsite) {
        this.empCompWebsite = empCompWebsite;
    }




}


