package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmployeeUsernameAndPassword generated by hbm2java
 */
@Entity
@Table(name="employee_username_and_password"
    ,catalog="onlinejobportal"
)
public class EmployeeUsernameAndPassword  implements java.io.Serializable {


     private String username;
     private String password;
     private Set<AuthTable2> authTable2s = new HashSet<AuthTable2>(0);

    public EmployeeUsernameAndPassword() {
    }

	
    public EmployeeUsernameAndPassword(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public EmployeeUsernameAndPassword(String username, String password, Set<AuthTable2> authTable2s) {
       this.username = username;
       this.password = password;
       this.authTable2s = authTable2s;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employeeUsernameAndPassword")
    public Set<AuthTable2> getAuthTable2s() {
        return this.authTable2s;
    }
    
    public void setAuthTable2s(Set<AuthTable2> authTable2s) {
        this.authTable2s = authTable2s;
    }




}


