package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faqs generated by hbm2java
 */
@Entity
@Table(name="faqs"
    ,catalog="onlinejobportal"
)
public class Faqs  implements java.io.Serializable {


     private Integer faqId;
     private String name;
     private String email;
    // private Integer mob;
     private String areaofconcern;
     private String description;

    public Faqs() {
    }

    public Faqs(String name, String email, String areaofconcern,String description) {
       this.name =name;
       this.email = email;
      //this.mob =mob;
     this.areaofconcern=areaofconcern;
     this.description=description;
    }
   @Column(name="name", nullable=false, length=45)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
   @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
//   @Column(name="mob", nullable=false, length=15)
//    public Integer getMob() {
//        return mob;
//    }
//
//    public void setMob(Integer mob) {
//        this.mob = mob;
//    }
   @Column(name="areaofconcern", nullable=false, length=100)
    public String getAreaofconcern() {
        return areaofconcern;
    }

    public void setAreaofconcern(String areaofconcern) {
        this.areaofconcern = areaofconcern;
    }
   @Column(name="description", nullable=false, length=1000)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Faq_id", unique=true, nullable=false)
    public Integer getFaqId() {
        return this.faqId;
    }
    
    public void setFaqId(Integer faqId) {
        this.faqId = faqId;
    }

    
   




}


